apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ant-media-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ant-media-server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
